format = """
[â•­](fg:current_line)\
$os\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$bun\
$deno\
$aws\
$cmd_duration\
$shell\
$username\
$line_break\
$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
# foreground = '#F8F8F2'
foreground = '#d1d1d1'
background = '#282A36'
current_line = '#252525'
primary = '#1E1F29'
box = '#252525'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'
#
# [os]
# format = '(fg:current_line)[î‚¶](fg:red)[$symbol ](fg:primary bg:red)[î‚´](fg:red)'
# disabled = false
#
# [os.symbols]
# Alpine = 'ïŒ€'
# Amazon = 'ï‰°'
# Android = 'îœ'
# Arch = 'ïŒƒ'
# CentOS = 'ïŒ„'
# Debian = 'ïŒ†'
# EndeavourOS = 'ïŒ¢'
# Fedora = 'ïŒŠ'
# FreeBSD = 'ïŒŒ'
# Garuda = 'ï…¼'
# Gentoo = 'ïŒ'
# Linux = 'ï…¼'
# Macos = 'ïŒ‚'
# Manjaro = 'ïŒ’'
# Mariner = 'ï…¼'
# Mint = 'ïŒ'
# NetBSD = 'ï…¼'
# NixOS = 'ïŒ“'
# OpenBSD = 'ïŒ¨'
# OpenCloudOS = 'î®ª'
# openEuler = 'ï…¼'
# openSUSE = 'ïŒ”'
# OracleLinux = 'âŠ‚âŠƒ'
# Pop = 'ïŒª'
# Raspbian = 'ïŒ•'
# Redhat = 'ïŒ–'
# RedHatEnterprise = 'ïŒ–'
# Solus = 'ïŒ­'
# SUSE = 'ïŒ”'
# Ubuntu = 'ïŒ›'
# Unknown = 'ï„ˆ'
# Windows = 'îœ'
#
[directory]
format = '[â”€](fg:current_line)[î‚¶](fg:box)[ó°· ](fg:foreground bg:box)[$path](fg:foreground bg:box)[î‚´](fg:box)'
# format = '[â”€](fg:current_line)[î‚¶](fg:pink)[ó°· ](fg:primary bg:pink)[î‚´](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[î‚´](fg:box)'
home_symbol = "~"

[git_branch]
# format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $branch](fg:foreground bg:box)'
format = '[â”€](fg:current_line)[î‚¶](fg:box)[$symbol](fg:green bg:box)[ $branch](fg:foreground bg:box)'
symbol = 'ï— '

[git_status]
format = '[( $all_status)](fg:foreground bg:box)[î‚´](fg:box)'

[nodejs]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]

[bun]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'ğŸ¥Ÿ'

[deno]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'ğŸ¦•'

[aws]
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[$symbol](fg:primary bg:purple)[î‚´](fg:purple bg:box)[ $profile](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'â˜ï¸'

[fill]
symbol = 'â”€'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[â”€](fg:current_line)[î‚¶](fg:box)[ïƒ§ ](fg:foreground bg:box)[ $duration ](fg:foreground bg:box)[î‚´](fg:box)'

[shell]
format = '[â”€](fg:current_line)[î‚¶](fg:box)[ï’‰ ](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[î‚´](fg:box)'
# format = '[â”€](fg:current_line)[î‚¶](fg:blue)[ï’‰ ](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[î‚´](fg:box)'
disabled = false

[time]
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[ó°¦– ](fg:primary bg:purple)[î‚´](fg:purple bg:box)[ $time](fg:foreground bg:box)[î‚´](fg:box)'
time_format = '%H:%M'
disabled = false

[username]
format = '[â”€](fg:current_line)[î‚¶](fg:box)[ï• ](fg:yellow bg:box)[ $user](fg:foreground bg:box)[î‚´](fg:box) '
# format = '[â”€](fg:current_line)[î‚¶](fg:yellow)[ï• ](fg:primary bg:yellow)[î‚´](fg:yellow bg:box)[ $user](fg:foreground bg:box)[î‚´](fg:box) '
show_always = true

[character]
format = """
[â”‚](fg:current_line)
[â•°â”€$symbol](fg:current_line) """
success_symbol = '[âœ](fg:bold foreground)'
error_symbol = '[Ã—](fg:bold red)'
